"""Phase 9: build the IEEE report PDF.

Copies the figures the report uses from results/ (they are generated by the pipeline scripts and never edited
by hand) into report/latex/figures/, then compiles report/latex/main.tex with Tectonic
(`brew install tectonic`) into report/Patel_ImageForgeryDetection_report.pdf.
Usage:  python scripts/build_report.py [--no-compile]
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys

from forgery.config import resolve

FIGURES = {   # name used in the LaTeX source -> generated file
    "fig_dataset_samples.png": "results/phase1/fig_samples.png",
    "fig_dataset_format.png": "results/phase1/fig_class_format.png",
    "fig_tampered_area.png": "results/phase1/fig_tampered_area.png",
    "fig_leakage.png": "results/phase2/fig_leakage.png",
    "fig_modules_R.png": "results/phase3/fig_modules_overview_R.png",
    "fig_ela_before_after.png": "results/phase3/fig_ela_before_after.png",
    "fig_dct_histogram.png": "results/phase3/fig_dct_histogram.png",
    "fig_copymove_matches.png": "results/phase3/fig_copymove_matches.png",
    "fig_sweeps.png": "results/phase4/fig_sweeps.png",
    "fig_roc_dev_R.png": "results/phase5/fig_roc_R.png",
    "fig_shap_R.png": "results/phase5/fig_shap_R.png",
    "fig_ablation.png": "results/phase5/fig_ablation.png",
    "fig_calibration_R.png": "results/phase5/fig_calibration_R.png",
    "fig_loc_methods_R.png": "results/phase6/fig_methods_R.png",
    "fig_loc_examples_R.png": "results/phase6/fig_examples_R.png",
    "fig_roc_test_R.png": "results/phase7/run_1/fig_roc_test_R.png",
    "fig_failures_R.png": "results/phase7/run_1/fig_failures_R.png",
    "fig_robustness.png": "results/phase7b/fig_robustness.png",
    "fig_synthetic_examples.png": "results/phase7b/fig_synthetic_examples.png",
    "fig_cnn_roc.png": "results/phase8/fig_roc_cnn_vs_classical.png",
    "fig_ela_examples.png": "results/phase8/fig_ela_examples.png",
    "fig_cnn_training.png": "results/phase8/fig_training_curves.png",
    "fig_ui_analyze.png": "results/phase8_5/ui_analyze.png",
    "fig_ui_evidence_maps.png": "results/phase8_5/ui_evidence_maps.png",
}
LATEX = resolve("report/latex")
PDF = resolve("report/Patel_ImageForgeryDetection_report.pdf")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-compile", action="store_true")
    args = ap.parse_args()
    (LATEX / "figures").mkdir(parents=True, exist_ok=True)
    missing = []
    for name, src in FIGURES.items():
        if resolve(src).exists():
            shutil.copy2(resolve(src), LATEX / "figures" / name)
        else:
            missing.append(src)
    if missing:
        sys.exit("missing figures (run the pipeline scripts first): " + ", ".join(missing))
    print(f"copied {len(FIGURES)} figures")
    if args.no_compile:
        return
    tectonic = shutil.which("tectonic")
    if tectonic is None:
        sys.exit("tectonic not found: brew install tectonic (or compile report/latex/main.tex with pdflatex+bibtex)")
    subprocess.run([tectonic, "--keep-logs", "main.tex"], cwd=LATEX, check=True)
    shutil.copy2(LATEX / "main.pdf", PDF)
    print(f"wrote {PDF}")


if __name__ == "__main__":
    main()
